Repository acm-ucr/ucr-hearts-website, pull requests merged in 2024-12, with the labels that each got.

#110 animation on about title
  src/components/about/AboutTitle.tsx
Labels: Ready to review

#112 Experience animation
  package-lock.json
  src/components/Footer.tsx
  src/components/about/Experience.tsx
Labels: about, Animation

#111 Footer responsiveness
  src/components/Footer.tsx
Labels: Mobile

#114 animated todo part of about page
  src/components/about/Description.tsx
  src/components/about/ToDo.tsx
Labels: about, Animation, Ready to review

#113 Animation for join.tsx
  src/components/home/Join.tsx
Labels: Fix Required

#119 Animated Eventcard.tsx and Eventcards.tsx
  src/components/events/EventCard.tsx
  src/components/events/EventCards.tsx
Labels: Animation, Ready to review

#120 animate com cards
  src/components/committee/ComCard.tsx
  src/components/committee/ComCards.tsx
Labels: Animation, Ready to review

#125 add mobile responsiveness for calendar
  src/components/events/CalendarCall.tsx
  src/components/ui/calendar.tsx
Labels: Ready to review, Mobile
