Repository acm-ucr/ucr-hearts-website, pull requests merged in 2024-10, with the labels that each got.

#39 ReviewTitle.tsx
  src/components/home/ReviewTitle.tsx
Labels: Ready to review

#34 add footer for all pages
  src/components/Footer.tsx
  src/data/footerLinks.js
  tailwind.config.ts
  tsconfig.json
Labels: Ready to review

#35 implemented AboutTitle.tsx
  src/components/about/AboutTitle.tsx
Labels: Ready to review

#38 Implimented Experience.tsx
  package-lock.json
  package.json
  src/components/about/Experience.tsx
Labels: about, Ready to review

#37 404 page with button
  package-lock.json
  package.json
  src/app/not-found.tsx
Labels: Ready to review

#40 Join.tsx
  package-lock.json
  src/components/home/Join.tsx
Labels: Fix Required

#43 the mentorship page
  package-lock.json
  src/components/about/Mentorship.tsx
Labels: about

#53 formating for event & eventlists
  package-lock.json
  src/components/events/Event.tsx
  src/components/events/EventList.tsx
Labels: Ready to review

#51 implement board
  public/boards/Ariel.webp
  public/boards/Jack.webp
  public/boards/Justin.webp
  public/boards/Purav.webp
  public/boards/Sarah.webp
  public/boards/Sarahc.webp
  src/components/boards/Board.tsx
  src/components/boards/BoardMembers.tsx
  src/components/events/Event.tsx
  src/components/home/Review.tsx
  src/data/boardInfo.js
  tailwind.config.ts
Labels: boards, Ready to review

#45 implement navigation
  src/components/Navigation.tsx
  src/data/navigation.js
Labels: Fix Required, Ready to review
