Repository acm-ucr/ucr-hearts-website, pull requests merged in 2024-11, with the labels that each got.

#64 Implimented Photo.tsx
  src/components/gallery/Photo.tsx
  src/components/gallery/Photos.tsx
Labels: Ready to review, gallery

#63 inegishi/implementeventCard
  src/components/events/EventCards.tsx
  src/data/eventCardInfo.js
Labels: Ready to review

#62 mapped eventInfo items
  src/components/events/EventList.tsx
  src/data/eventInfo.js
Labels: Ready to review

#60 Navigation_responsiveness
  src/components/Navigation.tsx
Labels: Ready to review, Mobile

#61 Landing responsiveness
  src/components/home/Landing.tsx
Labels: Ready to review, Mobile

#65 mapped review.tsx using an array.
  src/components/home/Review.tsx
  src/components/home/Reviews.tsx
  src/data/reviews.js
Labels: home, Ready to review

#58 imlemented ComCard.tsx and ComCards.tsx
  src/app/committee/page.tsx
  src/components/committee/ComCard.tsx
  src/components/committee/ComCards.tsx
Labels: Ready to review

#59 implement board card flip animations
  package-lock.json
  package.json
  src/components/boards/Board.tsx
Labels: boards, Ready to review

#66 mapping ComCards
  src/app/committee/page.tsx
  src/components/committee/ComCards.tsx
  src/data/comCardInfo.js
  tailwind.config.ts
Labels: Ready to review

#78 Implemented mobile responsiveness
  src/components/home/Review.tsx
  src/components/home/ReviewTitle.tsx
  src/components/home/Reviews.tsx
Labels: Ready to review

#79 improve mobile responsiveness for Join.tsx
  src/components/home/Join.tsx
Labels: Ready to review

#80 inegishi/mobile
  src/components/events/EventCard.tsx
  src/components/events/EventCards.tsx
Labels: Ready to review

#81 Implimented Photos.tsx
  package-lock.json
  package.json
  src/components/gallery/Photo.tsx
  src/components/gallery/Photos.tsx
  src/data/boardInfo.js
  src/data/photosInfo.js
Labels: Ready to review, gallery

#82 mobile responsiveness abouttitle.tsx
  src/components/about/AboutTitle.tsx
Labels: Ready to review

#90 implement calendar
  components.json
  eslint.config.mjs
  package-lock.json
  package.json
  src/app/events/page.tsx
  src/app/globals.css
  src/components/events/Calendar.tsx
  src/components/events/CalendarCall.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/lib/utils.ts
  tailwind.config.js
Labels: events

#94 Improved mobile responsiveness for photo.tsx and photos.tsx
  package-lock.json
  src/components/gallery/Photo.tsx
  src/components/gallery/Photos.tsx
Labels: Ready to review, Mobile

#96 fixed mobile responsiveness with comcards
  package-lock.json
  src/components/committee/ComCard.tsx
  src/components/committee/ComCards.tsx
  tsconfig.json
Labels: Ready to review
